
# Generated by Django 3.2.6 on 2021-08-25 17:00
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_actor',
            name='actor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_actor', to='movies.actor'),
        ),
        migrations.AlterField(
            model_name='movie_actor',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_actor', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='movie_director',
            name='director_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_director', to='movies.director'),
        ),
        migrations.AlterField(
            model_name='movie_director',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_director', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='movie_genre',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_genre', to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='movie_genre',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_genre', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='movie_keyword',
            name='keyword_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_keyword', to='movies.keyword'),
        ),
        migrations.AlterField(
            model_name='movie_keyword',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_keyword', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='user_keyword',
            name='keyword_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_keyword', to='movies.keyword'),
        ),
        migrations.AlterField(
            model_name='user_keyword',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_keyword', to='movies.user'),
        ),
        migrations.AlterField(
            model_name='user_movie',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movie', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='user_movie',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movie', to='movies.user'),
        ),
    ]
