# Generated by Django 3.2.6 on 2021-08-30 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210826_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='owner',
            field=models.ManyToManyField(through='movies.Movie_Actor', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='director',
            name='owner',
            field=models.ManyToManyField(through='movies.Movie_Director', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='genre',
            name='owner',
            field=models.ManyToManyField(through='movies.Movie_Genre', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='owner_movie',
            field=models.ManyToManyField(through='movies.Movie_Keyword', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='owner_user',
            field=models.ManyToManyField(through='movies.User_Keyword', to='movies.User'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='director',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(blank=True, default=0, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='User_Movie',
        ),
        migrations.AddField(
            model_name='movie_user',
            name='movie_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_movie', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='movie_user',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_movie', to='movies.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.ManyToManyField(through='movies.Movie_user', to='movies.Movie'),
        ),
    ]
