# Generated by Django 3.2.6 on 2021-09-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20210920_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='name_id',
            new_name='user_id',
        ),
    ]
