# Generated by Django 3.2.6 on 2021-09-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_rename_name_id_likes_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Querylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=100)),
            ],
        ),
    ]
